### ISSUE TITLE
grabserial stops printing 

### ISSUE THREAD

**Issue by embLin** [tbird20d/grabserial#2] opened 2013-12-17 15:12 UTC
Hi,

I used grabserial for checking the startupcode by using the serial port of my target device, on the host side it's connected to a ttyUSB Port.

When I start grabserial only a few messages are shown and it stops printing out the lines (i know there are more, since i usually communicate with other serial programs like putty, without any problems). The program doesn't quit, it just freezes, i have to break it with [CTRL-C].

For debugging reasons, I added a loop at my startup, and then it printed out everything. So what i guess: the script is a bit slow on processing, since it only prints messages out as long as it physically receives anything. I already tried to force printing out the missing message by some flush commands, without any success.

 I like that script, the results come in quiet handy, but unfortunately I can't use it as it is at the moment.

**Comment by tbird20d** [comment] 2015-03-27 15:33
Sorry we couldn't get to the bottom of this.  I've seen strange stuff when there were other readers of the serial port active (and they are consuming some of the characters from the device).  This report is, by now, quite old.  I'm closing this issue, as I can't reproduce it, and don't have any way to proceed.
 -- Tim

**Closed by tbird20d** 2015-03-27 15:33 UTC
